"""Deterministic encoding and hashing.

Every hash in this codebase is a stable identifier that must survive process restarts,
code reordering and - during the port - a change of implementation language. ``run_id``,
``batch_id``, ``alert_id`` and the document hash are all derived here, so a difference in
this module is a difference in identity.

The encoding is byte-compatible with the superseded JavaScript implementation on purpose:
that is what lets the two implementations be run against the same fixtures and compared
row for row. ``tests/unit/test_hashing.py`` pins that with reference values generated by
the JavaScript implementation.

``json.dumps`` is not usable directly. Its key order is insertion order, so two logically
identical mappings can serialize differently; keys are therefore sorted, and every scalar
is length-prefixed to remove concatenation ambiguity - ``"ab" + "c"`` must not encode the
same as ``"a" + "bc"``.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping, Sequence
from typing import Any

__all__ = ["canonical_encode", "compact_json", "sha256_of", "sha256_text"]


def compact_json(value: Any) -> str:
    """Serialize a value for storage, compactly and in insertion order.

    Used for the JSON-valued audit columns - the representative document, the panel
    parse result, the evidence list. Insertion order is preserved rather than sorted
    because these columns are read by people: the fields stay in the order the
    pipeline produced them. Hashed values go through :func:`canonical_encode`
    instead, which sorts.

    The separators are explicit so the stored bytes do not depend on the default
    spacing of whichever json implementation is in use.
    """
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False, default=str)


def _number_to_string(value: float | int) -> str:
    """Format a number the way JavaScript's ``String(n)`` does.

    Python renders ``42.0`` as ``"42.0"`` where JavaScript renders ``"42"``. Since the
    encoding must match across implementations, a float with an integral value is written
    without its fractional part.
    """
    if isinstance(value, bool):  # bool is an int subclass; callers handle it first
        raise TypeError("bool must be encoded as a boolean, not a number")
    if isinstance(value, int):
        return str(value)
    if not math.isfinite(value):
        raise TypeError(f"cannot encode non-finite number: {value}")
    if value == int(value):
        # Also normalizes -0.0 to 0, matching the JavaScript encoder.
        return str(int(value))
    return repr(value)


def canonical_encode(value: Any) -> str:
    """Return an unambiguous, order-independent encoding of ``value``."""
    if value is None:
        return "n"
    if isinstance(value, bool):
        return "b1" if value else "b0"
    if isinstance(value, int | float):
        text = _number_to_string(value)
        return f"d{len(text)}:{text}"
    if isinstance(value, str):
        return f"s{len(value.encode('utf-8'))}:{value}"
    if isinstance(value, Mapping):
        keys = sorted(value.keys())
        parts = "".join(f"{canonical_encode(k)}{canonical_encode(value[k])}" for k in keys)
        return f"o{len(keys)}:{parts}"
    if isinstance(value, Sequence):
        parts = "".join(canonical_encode(item) for item in value)
        return f"a{len(value)}:{parts}"
    raise TypeError(f"cannot encode value of type {type(value).__name__}")


def sha256_of(value: Any) -> str:
    """SHA-256 of the canonical encoding of ``value``, as lowercase hex."""
    return hashlib.sha256(canonical_encode(value).encode("utf-8")).hexdigest()


def sha256_text(text: str) -> str:
    """SHA-256 of raw text exactly as supplied.

    Used where the bytes themselves are the identity: registry file contents, serialized
    LLM payloads, and panel SQL text.
    """
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
