"""Acceptance verification (design section 7.5, acceptance-data contract).

Runs the acceptance teams against the mock and compares the PERSISTED SQL rows and the
rendered CSV exports against ``test/fixtures/expected-results.json``.

The manifest is hand-authored from the fixture definitions and is never generated by this
pipeline: an oracle produced by the code under test would agree with any bug that happened
to be self-consistent. It is also carried over from the JavaScript implementation
unchanged, which is what lets it detect a behavioural difference introduced by the port.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from alerts_bi_operations.report.render import render_run_report
from alerts_bi_shared.db.connection import connect
from alerts_bi_shared.timefmt import iso_instant

from ..config import AppConfig
from ..db.repositories import (
    get_daily_metrics,
    get_findings,
    get_rule_counts,
    get_run,
    persist_run,
)
from ..es.client import EsClient
from ..llm.fake import FakeLlmClient
from ..llm.grouping import build_batches
from .orchestrator import execute_run

__all__ = ["MANIFEST_PATH", "Failure", "VerificationResult", "verify_acceptance"]

MANIFEST_PATH = Path("test") / "fixtures" / "expected-results.json"

#: Derived rates are persisted as DECIMAL(18,6), so a daily alerts_per_hour of 1/24 reads
#: back as 0.041667. The manifest records the exact arithmetic and the comparison allows
#: the rounding that storage introduces - anything larger than half a unit in the last
#: stored place is a real disagreement.
_TOLERANCE = 5e-7


@dataclass(frozen=True, slots=True)
class Failure:
    where: str
    expected: Any
    actual: Any


@dataclass(slots=True)
class VerificationResult:
    checks: int = 0
    failures: list[Failure] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.failures

    def equal(self, where: str, expected: Any, actual: Any) -> None:
        self.checks += 1
        if isinstance(expected, int | float) and not isinstance(expected, bool):
            same = actual is not None and abs(_number(actual) - float(expected)) <= _TOLERANCE
        elif expected is None or actual is None:
            same = expected == actual
        else:
            same = str(expected) == str(actual)
        if not same:
            self.failures.append(Failure(where, expected, actual))

    def deep_equal(self, where: str, expected: Any, actual: Any) -> None:
        self.checks += 1
        if json.dumps(expected, sort_keys=True) != json.dumps(actual, sort_keys=True):
            self.failures.append(Failure(where, expected, actual))


def _number(value: Any) -> float:
    if isinstance(value, Decimal):
        return float(value)
    return float(value)


def _nullable_number(value: Any) -> float | None:
    """A stored value that may be NULL, such as ``unseen`` on a schema with no panel.

    NULL stays None so a manifest ``null`` can match it, and a manifest number against a
    NULL is reported as a mismatch rather than raising.
    """
    return None if value is None else _number(value)


def _nullable_bool(value: Any) -> bool | None:
    """A BIT column read back as bool, 0/1 or NULL."""
    return None if value is None else bool(value)


def _nullable_sum(values: Sequence[Any]) -> float | None:
    """Sum a nullable column: NULL when every value is NULL, which means "not measured".

    A schema either has a panel or not, so its buckets are all NULL or all numbers.
    """
    present = [_number(value) for value in values if value is not None]
    if not present and values:
        return None
    return sum(present)


def _date_key(value: Any) -> str:
    if isinstance(value, datetime | date):
        return value.isoformat()[:10]
    return str(value)[:10]


_SUM_FIELDS = (
    "alerts",
    "flagged_by_rule",
    "flagged_by_llm",
    "suppressed",
    "suppression_unmeasured",
    "node_name_numerator",
    "node_name_denominator",
    "key_inflation_numerator",
    "key_inflation_denominator",
)

_SUM_ALIASES = {
    "distinct_sum": "distinct_alerts",
    "flagged_by_rule_distinct_sum": "flagged_by_rule_distinct",
    "flagged_by_llm_distinct_sum": "flagged_by_llm_distinct",
    "needs_review_sum": "needs_review",
    "assessed_good_sum": "assessed_good",
    "unassessed_sum": "unassessed",
    "phase2_gaps_sum": "phase2_gaps",
}


#: Daily columns that are NULL when the schema has no supplied panel (team summary spec 6).
_NULLABLE_SUM_FIELDS = ("unseen", "unseen_unmeasured")

#: Per-alert work-list values the manifest's ``fire_patterns`` block pins: the R6 facts
#: judged by firing episodes and the pattern derived from them (design section 7.14).
_FIRE_PATTERN_FIELDS = (
    "fire_pattern",
    "clear_count",
    "max_clear_cycles_24h",
    "max_episode_firing_rows",
    "open_since",
)


def _fact(finding: Mapping[str, Any], name: str) -> Any:
    """One stored R6 fact, with ``open_since`` in the pipeline's one instant format.

    A column the work list does not carry reads as None, so it fails as a mismatch against
    the manifest instead of raising.
    """
    value = finding.get(name)
    if name == "open_since" and isinstance(value, datetime):
        return iso_instant(value)
    return value


def _sum_daily(daily: Sequence[Mapping[str, Any]]) -> dict[str, float | None]:
    totals: dict[str, float | None] = {
        name: sum(_number(row[name]) for row in daily) for name in _SUM_FIELDS
    }
    for alias, column in _SUM_ALIASES.items():
        totals[alias] = sum(_number(row[column]) for row in daily)
    for name in _NULLABLE_SUM_FIELDS:
        totals[name] = _nullable_sum([row.get(name) for row in daily])
    return totals


def _ratio(numerator: float | None, denominator: float | None) -> float | None:
    if numerator is None or not denominator:
        return None
    return numerator / denominator


def _verify_alerts(
    check: VerificationResult,
    team_id: str,
    findings: Sequence[Mapping[str, Any]],
    expected: Mapping[str, Any],
) -> None:
    """Compare per-alert work-list values against the ``fire_patterns`` and ``unseen`` blocks.

    Both are keyed by schema, then ``key_field``. A listed alert missing from the work list
    is a failure, not a skip.
    """
    by_key = {(str(f["alert_schema"]), str(f["key_field"])): f for f in findings}

    def lookup(schema: str, key_field: str, where: str) -> Mapping[str, Any] | None:
        finding = by_key.get((schema, key_field))
        if finding is None:
            check.checks += 1
            check.failures.append(Failure(where, "present in the work list", "missing"))
        return finding

    for schema, alerts in expected.get("fire_patterns", {}).items():
        for key_field, fields in alerts.items():
            where = f"{team_id}.{schema}.fire_patterns.{key_field}"
            finding = lookup(schema, key_field, where)
            if finding is None:
                continue
            for name in _FIRE_PATTERN_FIELDS:
                if name in fields:
                    check.equal(f"{where}.{name}", fields[name], _fact(finding, name))

    for schema, block in expected.get("unseen", {}).items():
        for key_field, value in block.get("worklist_unseen", {}).items():
            where = f"{team_id}.{schema}.unseen.worklist.{key_field}"
            finding = lookup(schema, key_field, where)
            if finding is not None:
                check.equal(where, value, _nullable_bool(finding["unseen"]))


def _verify_team(
    check: VerificationResult,
    team_id: str,
    expected: Mapping[str, Any],
    run: Mapping[str, Any],
    daily: Sequence[Mapping[str, Any]],
    rule_counts: Sequence[Mapping[str, Any]],
    findings: Sequence[Mapping[str, Any]],
    batches: Sequence[Any],
) -> None:
    check.equal(f"{team_id}.phase_derived", expected["phase_derived"], run["phase_derived"])
    check.equal(
        f"{team_id}.phase2_readiness_pct",
        expected["phase2_readiness_pct"],
        None if run["phase2_readiness_pct"] is None else _number(run["phase2_readiness_pct"]),
    )

    # Identity states are mutually exclusive, so the counts must partition the work list.
    states: dict[str, int] = {}
    for finding in findings:
        key = str(finding["quality_state"])
        states[key] = states.get(key, 0) + 1
    expected_states = expected.get("identity_states", {})
    for state, count in expected_states.items():
        check.equal(f"{team_id}.identity_states.{state}", count, states.get(state, 0))
    check.equal(f"{team_id}.identity_states.total", sum(expected_states.values()), len(findings))

    for schema, expected_schema in expected.get("schemas", {}).items():
        schema_daily = [d for d in daily if d["alert_schema"] == schema]
        check.equal(
            f"{team_id}.{schema}.identities",
            expected_schema["identities"],
            len([f for f in findings if f["alert_schema"] == schema]),
        )

        totals = _sum_daily(schema_daily)
        for field_name, value in expected_schema.get("totals", {}).items():
            where = f"{team_id}.{schema}.totals.{field_name}"
            if field_name == "distinct_per_day":
                check.equal(where, value, _ratio(totals["distinct_sum"], 7))
            elif field_name == "alerts_per_hour":
                check.equal(where, value, _ratio(totals["alerts"], 168))
            elif field_name == "node_name_ratio":
                check.equal(
                    where,
                    value,
                    _ratio(totals["node_name_numerator"], totals["node_name_denominator"]),
                )
            elif field_name == "key_inflation_ratio":
                check.equal(
                    where,
                    value,
                    _ratio(totals["key_inflation_numerator"], totals["key_inflation_denominator"]),
                )
            else:
                check.equal(where, value, totals[field_name])

        # Buckets the manifest does not mention must exist and be entirely zero: a missing
        # day would otherwise pass unnoticed.
        by_date = {_date_key(d["snapshot_date"]): d for d in schema_daily}
        expected_daily = expected_schema.get("daily", {})
        for date_key, expected_day in expected_daily.items():
            actual_day = by_date.get(date_key)
            if actual_day is None:
                check.checks += 1
                check.failures.append(
                    Failure(f"{team_id}.{schema}.daily.{date_key}", "present", "missing")
                )
                continue
            for field_name, value in expected_day.items():
                check.equal(
                    f"{team_id}.{schema}.daily.{date_key}.{field_name}",
                    value,
                    _nullable_number(actual_day[field_name]),
                )
        for date_key, day in by_date.items():
            if date_key in expected_daily:
                continue
            check.equal(
                f"{team_id}.{schema}.daily.{date_key}.alerts (unlisted must be zero)",
                0,
                day["alerts"],
            )
            check.equal(
                f"{team_id}.{schema}.daily.{date_key}.flagged_by_rule (unlisted must be zero)",
                0,
                day["flagged_by_rule"],
            )

        # Per-rule counts, including that no unexpected rule fired.
        schema_rules = [r for r in rule_counts if r["alert_schema"] == schema]
        actual_rules: dict[str, dict[str, list[int]]] = {}
        for row in schema_rules:
            actual_rules.setdefault(_date_key(row["snapshot_date"]), {})[str(row["rule_id"])] = [
                int(row["match_count"]),
                int(row["distinct_count"]),
            ]
        expected_rules = expected_schema.get("rule_counts", {})
        for date_key, rules in expected_rules.items():
            for rule_id, pair in rules.items():
                check.deep_equal(
                    f"{team_id}.{schema}.rule_counts.{date_key}.{rule_id}",
                    pair,
                    actual_rules.get(date_key, {}).get(rule_id),
                )
        expected_keys = {
            f"{date_key}|{rule_id}"
            for date_key, rules in expected_rules.items()
            for rule_id in rules
        }
        for row in schema_rules:
            key = f"{_date_key(row['snapshot_date'])}|{row['rule_id']}"
            if key not in expected_keys:
                check.checks += 1
                check.failures.append(
                    Failure(
                        f"{team_id}.{schema}.rule_counts.{key}",
                        "no finding",
                        [int(row["match_count"]), int(row["distinct_count"])],
                    )
                )

    if "suppression" in expected:
        suppression = expected["suppression"]
        check.equal(
            f"{team_id}.suppression.suppressed_rows",
            suppression["suppressed_rows"],
            sum(_number(d["suppressed"]) for d in daily),
        )
        check.equal(
            f"{team_id}.suppression.unmeasured_leaves",
            suppression["unmeasured_leaves"],
            sum(_number(d["suppression_unmeasured"]) for d in daily),
        )
        suppressed_nodes = sorted(
            str(f["node_name"]) for f in findings if "R5" in str(f["core_rule_ids"]).split(",")
        )
        if "suppressed_node_names" in suppression:
            check.deep_equal(
                f"{team_id}.suppression.suppressed_node_names",
                sorted(suppression["suppressed_node_names"]),
                suppressed_nodes,
            )
        for name in suppression.get("not_suppressed_node_names", []):
            check.equal(
                f"{team_id}.suppression.not_suppressed.{name}", False, name in suppressed_nodes
            )

    for schema, block in expected.get("unseen", {}).items():
        schema_daily = [d for d in daily if d["alert_schema"] == schema]
        for name, column in (("unseen_rows", "unseen"), ("unseen_unmeasured", "unseen_unmeasured")):
            if name in block:
                check.equal(
                    f"{team_id}.{schema}.unseen.{name}",
                    block[name],
                    _nullable_sum([d.get(column) for d in schema_daily]),
                )

    _verify_alerts(check, team_id, findings, expected)

    if "llm_batches" in expected:
        expected_batches = expected["llm_batches"]
        check.equal(f"{team_id}.llm_batches.total", expected_batches["total"], len(batches))
        sizes_by_group: dict[str, list[int]] = {}
        for batch in batches:
            sizes_by_group.setdefault(batch.group_value, []).append(len(batch.alerts))
        for group, sizes in expected_batches["partition_sizes_by_group"].items():
            check.deep_equal(f"{team_id}.llm_batches.{group}", sizes, sizes_by_group.get(group))


def _read_csv_lines(path: Path) -> list[str]:
    """Read a rendered CSV back without newline translation.

    The exports use CRLF per RFC 4180. Reading them through Python's universal-newline
    handling rewrites CRLF to LF, so a CRLF split would then find a single line and every
    row count would silently verify as zero.
    """
    return path.read_bytes().decode("utf-8").strip().split("\r\n")


def _verify_csv(
    check: VerificationResult,
    team_id: str,
    out_dir: Path,
    daily: Sequence[Mapping[str, Any]],
    findings: Sequence[Mapping[str, Any]],
) -> None:
    """Cross-check the rendered CSV against the persisted rows it was rendered from."""
    for name in ("daily_metrics.csv", "rule_counts.csv", "alert_worklist.csv"):
        check.equal(f"{team_id}.csv.{name} exists", True, (out_dir / name).exists())

    daily_lines = _read_csv_lines(out_dir / "daily_metrics.csv")
    check.equal(f"{team_id}.csv.daily_metrics rows", len(daily), len(daily_lines) - 1)

    headers = daily_lines[0].split(",")
    alerts_index = headers.index("alerts")
    csv_alerts = sum(int(line.split(",")[alerts_index]) for line in daily_lines[1:])
    check.equal(
        f"{team_id}.csv.daily_metrics alerts total",
        sum(_number(d["alerts"]) for d in daily),
        csv_alerts,
    )

    # One row per identity, never divided by seven.
    worklist_lines = _read_csv_lines(out_dir / "alert_worklist.csv")
    check.equal(f"{team_id}.csv.alert_worklist rows", len(findings), len(worklist_lines) - 1)


def verify_acceptance(
    *,
    config: AppConfig,
    manifest_path: str | None = None,
    out_dir: str | None = None,
    database: str | None = None,
) -> VerificationResult:
    """Run acceptance verification against the mock and the manifest."""
    manifest = json.loads(Path(manifest_path or MANIFEST_PATH).read_bytes().decode("utf-8"))
    run_at = datetime.fromisoformat(str(manifest["run_at"]).replace("Z", "+00:00")).astimezone(UTC)
    es_client = EsClient(config.es)
    check = VerificationResult()
    base_out = Path(out_dir or Path("out") / "acceptance")

    with connect(config.sql, database or config.sql.database) as db:
        for team_id, expected in manifest["teams"].items():
            payload, summary = execute_run(
                team_id=team_id,
                run_at=run_at,
                config=config,
                es_client=es_client,
                llm_client=FakeLlmClient(),
                # No db: acceptance always classifies fresh, so a verdict stored by an
                # earlier verification run cannot mask a regression in the assessment path.
                db=None,
            )
            persist_run(db, payload)

            team_out = base_out / team_id
            render_run_report(db, summary.run_id, team_out)

            run = get_run(db, summary.run_id)
            assert run is not None
            daily = get_daily_metrics(db, summary.run_id)
            rule_counts = get_rule_counts(db, summary.run_id)
            findings = get_findings(db, summary.run_id)

            # Batch shapes are recomputed from the persisted eligible set so partition
            # sizes can be asserted independently of whether the model was called.
            eligible = [
                _EligibleAlert(
                    application=str(f["application"]),
                    key_field=str(f["key_field"]),
                    schema=str(f["alert_schema"]),
                    alert_rule_url=f["alert_rule_url"],
                )
                for f in findings
                if f["quality_state"] != "rule_flagged"
            ]
            batches = build_batches(
                eligible,  # type: ignore[arg-type]
                summary.run_id,
                str(run["prompt_version"]),
                str(run["model_version"] or "fake-model-1"),
            )

            _verify_team(check, team_id, expected, run, daily, rule_counts, findings, batches)
            _verify_csv(check, team_id, team_out, daily, findings)

            # The window contract is identical for every team.
            v1_daily = [d for d in daily if d["alert_schema"] == "v1"]
            check.equal(
                f"{team_id}.window.bucket_count", manifest["window"]["bucket_count"], len(v1_daily)
            )
            check.equal(
                f"{team_id}.window.covered_hours_total",
                manifest["window"]["covered_hours_total"],
                sum(_number(d["covered_hours"]) for d in v1_daily),
            )

    return check


@dataclass(frozen=True, slots=True)
class _EligibleAlert:
    """The few attributes ``build_batches`` reads, reconstructed from persisted rows."""

    application: str
    key_field: str
    schema: str
    alert_rule_url: str | None
