"""Hashing parity with the superseded JavaScript implementation.

The expected values below were produced by the JavaScript implementation at the
``javascript-mvp`` tag. They are pinned here because ``run_id``, ``batch_id``,
``alert_id`` and the representative-document hash are all derived from this encoding: if
it drifts, two implementations that are otherwise identical produce different identities
and the parity comparison becomes meaningless.
"""

from __future__ import annotations

import pytest
from alerts_bi_shared.hashing import canonical_encode, sha256_of, sha256_text

# (label, value, expected encoding, expected sha256) - generated by the JavaScript build.
JS_REFERENCE = [
    ("null", None, "n", "1b16b1df538ba12dc3f97edbb85caa7050d46c148134290feba80f8236c83db9"),
    ("true", True, "b1", "7dc96f776c8423e57a2785489a3f9c43fb6e756876d6ad9a9cac4aa4e72ec193"),
    ("false", False, "b0", "c02c0b965e023abee808f2b548d8d5193a8b5229be6f3121a6f16e2d41a449b3"),
    ("int", 42, "d2:42", "1b732fd77631e83f38482a142d321061775f293b31c3a592a6d9ef6468c072c1"),
    ("float", 1.5, "d3:1.5", "24cfbcfdf6c08b1a7132fdf58e523c4d32d12980071a90df873d0cdff97f89ef"),
    ("negzero", -0.0, "d1:0", "406b2b52b84c9e25ad1c898f522f1ba3330a3c0e223cdcfd8225cc2608b669e1"),
    ("emptystr", "", "s0:", "fb912574cecad54c6a0bc75b46172350b6374929d602d5fbcb4ca0ec831fd532"),
    ("ascii", "abc", "s3:abc", "4773c535ad69b2967b18f9178f4dd697e226dd58f8ffd0bab9df42ab112a5e3b"),
    (
        "unicode",
        "héllo — wörld",
        "s17:héllo — wörld",
        "e205e367a173929aa32ee44582d69e84ef5038b4727b10214416013ba8a93662",
    ),
    (
        "array",
        ["a", "b"],
        "a2:s1:as1:b",
        "32d80e74b0505f3e5390ac0d078127c9ab9d7e108fb9148fd847699736d68723",
    ),
    (
        "nested",
        {"b": 1, "a": "x", "c": [True, None]},
        "o3:s1:as1:xs1:bd1:1s1:ca2:b1n",
        "ec5bfc0506dc5001cf2a463fdfff35b9da7b77f5e726abcd7800306d3e6acffd",
    ),
    (
        "docish",
        {
            "application": "app-1",
            "key_field": "k",
            "@timestamp": "2026-08-20T12:00:00.000Z",
            "node_name": None,
        },
        "o4:s10:@timestamps24:2026-08-20T12:00:00.000Zs11:applications5:app-1s9:key_fields1:ks9:node_namen",
        "35ff20fe9ea458a251130277d0fb8c838d0768747e971d2aac276f0d634d581a",
    ),
]


@pytest.mark.parametrize(("label", "value", "encoding", "digest"), JS_REFERENCE)
def test_encoding_matches_the_javascript_implementation(
    label: str, value: object, encoding: str, digest: str
) -> None:
    assert canonical_encode(value) == encoding, label
    assert sha256_of(value) == digest, label


def test_sha256_text_matches_the_javascript_implementation() -> None:
    assert sha256_text("abc") == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    assert (
        sha256_text("héllo") == "3c48591d8d098a4538f5e013dfcf406e948eac4d3277b10bf614e295d6068179"
    )


def test_key_order_does_not_change_the_encoding() -> None:
    assert sha256_of({"a": 1, "b": 2}) == sha256_of({"b": 2, "a": 1})


def test_content_changes_the_encoding() -> None:
    assert sha256_of({"a": 1}) != sha256_of({"a": 2})
    assert sha256_of({"a": 1}) != sha256_of({"b": 1})


def test_length_prefixing_prevents_a_shifted_boundary_collision() -> None:
    assert canonical_encode(["ab", "c"]) != canonical_encode(["a", "bc"])
    assert canonical_encode({"a": "bc"}) != canonical_encode({"ab": "c"})


def test_a_float_with_an_integral_value_encodes_like_an_integer() -> None:
    # JavaScript renders String(42.0) as "42"; Python's str would give "42.0".
    assert canonical_encode(42.0) == canonical_encode(42)


def test_non_finite_numbers_are_rejected() -> None:
    with pytest.raises(TypeError, match="non-finite"):
        canonical_encode(float("inf"))
    with pytest.raises(TypeError, match="non-finite"):
        canonical_encode(float("nan"))


def test_an_unencodable_type_fails_loudly() -> None:
    with pytest.raises(TypeError, match="cannot encode"):
        canonical_encode(object())
